### ISSUE TITLE
Crash issue in 32bit game alpha release

### ISSUE THREAD

**Issue by caronteaysam** [gustavohmsilva/NoManaMage#1]
Game crash in first passage on win32 bit game version

**Crash files:** [crash.zip](https://github.com/gustavohmsilva/NoManaMage/files/5053591/crash.zip)

![image](https://user-images.githubusercontent.com/58921291/89834396-26469480-db39-11ea-8ae8-bb9e2fd9b22c.png)

**Comment by gustavohmsilva** [comment]
Defold developers pointed out that windows 32 bits version is somewhat problematic. This is being defines as non-important at the moment.
